// frontend/src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// --- YENİ EKLENEN IMPORT ---
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Santral Finansal Risk Paneli",
  description: "Generated by our project",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr">
      <body className="bg-base-dark text-text-light">
        {/* --- YENİ EKLENEN TOASTER COMPONENT'İ --- */}
        {/* Bu component, bildirimlerin nerede ve nasıl görüneceğini ayarlar. */}
        <Toaster 
          position="top-right" // Bildirimler sağ üst köşede çıksın
          toastOptions={{
            // Varsayılan stil ayarları
            style: {
              background: '#161B22', // component-dark rengimiz
              color: '#E6EDF3',      // text-light rengimiz
              border: '1px solid #30363D', // border-dark rengimiz
            },
            // Başarı bildirimleri için özel stil
            success: {
              iconTheme: {
                primary: '#39FF14', // brand-green rengimiz
                secondary: '#0D1117', // base-dark rengimiz
              },
            },
            // Hata bildirimleri için özel stil
            error: {
              iconTheme: {
                primary: '#ef4444', // red-500
                secondary: '#FFFFFF',
              },
            },
          }}
        />
        {children}
      </body>
    </html>
  );
}
