[package]
name    = "backend"
version = "0.1.0"
edition = "2024"

# -------------------------------------------------
# RUNTIME & WEB
# -------------------------------------------------
[dependencies]
<<<<<<< HEAD
actix-cors = "0.7.1"
actix-web = "4"
bigdecimal = { version = "0.3.1", features = ["serde"] }
chrono = { version = "0.4.41", features = ["serde"] }
dotenvy = "0.15" # .env dosyasını okumak için
env_logger = "0.11.8"
log = "0.4.27"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "json", "bigdecimal"] }
uuid = { version = "1.17.0", features = ["serde", "v4"] }
argon2 = "0.5"
password-hash = "0.5"   # genellikle argon2 ile gelir ama açık eklemek iyi
futures = "0.3"
jsonwebtoken = "9"
anyhow = "1"
actix-web-actors = "4"
actix = "0.13"
urlencoding = "2"
=======
actix-web  = "4.5"
actix-cors = "0.7"
tokio      = { version = "1.38", features = ["macros", "rt-multi-thread"] }

# -------------------------------------------------
# SERDE / JSON / LOG
# -------------------------------------------------
serde       = { version = "1.0", features = ["derive"] }
serde_json  = "1.0"
log         = "0.4"
env_logger  = "0.11"
dotenvy     = "0.15"

# -------------------------------------------------
# AUTH / SECURITY
# -------------------------------------------------
argon2         = "0.5"
password-hash  = "0.5"
jsonwebtoken   = "9"
rand           = { version = "0.9", features = ["std_rng"] }

# -------------------------------------------------
# DATA / TIME / NUMERIC
# -------------------------------------------------
uuid        = { version = "1", features = ["v4", "serde"] }
chrono      = { version = "0.4", features = ["serde"] }
bigdecimal = { version = "0.3", features = ["serde"] }

# -------------------------------------------------
# DATABASE (sqlx + Postgres)
# -------------------------------------------------
sqlx = { version = "0.7", features = [
    "runtime-tokio-native-tls",
    "postgres",
    "macros",
    "chrono",
    "uuid",
    "json",
    "bigdecimal"
] }
# -------------------------------------------------
# MISC
# -------------------------------------------------
futures = "0.3"
serde_with = "3.14.0"
>>>>>>> ac6ae1aab7b9915e4d91c0e28a19794566b4096e
